structureJS.module('GeoInfo-US', function(require){

return {
  states : ['ALABAMA' ,
            'ALASKA' ,	
            'ARIZONA' ,	
            'ARKANSAS', 
            'CALIFORNIA' ,
            'COLORADO' , 
            'CONNECTICUT' ,	
            'DELAWARE' ,
            'FLORIDA'	, 
            'GEORGIA'	,
            'HAWAII', 
            'IDAHO' ,	
            'ILLINOIS', 	
            'INDIANA' ,	
            'IOWA' ,	
            'KANSAS' ,	
            'KENTUCKY' ,	
            'LOUISIANA' ,	
            'MAINE' ,	
            'MARYLAND' ,	
            'MASSACHUSETTS' ,	
            'MICHIGAN' ,
            'MINNESOTA'	, 
            'MISSISSIPPI'	, 
            'MISSOURI' ,	
            'MONTANA'	, 
            'NEBRASKA'	, 
            'NEVADA'	, 
            'NEW HAMPSHIRE'	,
            'NEW JERSEY' ,	
            'NEW MEXICO' ,	
            'NEW YORK' ,	
            'NORTH CAROLINA' ,	
            'NORTH DAKOTA'	, 
            'OHIO'	, 
            'OKLAHOMA' ,	
            'OREGON'	, 
            'PENNSYLVANIA' ,	
            'RHODE ISLAND' ,	
            'SOUTH CAROLINA' ,	
            'SOUTH DAKOTA'	, 
            'TENNESSEE'	, 
            'TEXAS'	,
            'UTAH'	, 
            'VERMONT'	, 
            'VIRGINIA'	, 
            'WASHINGTON'	, 
            'WEST VIRGINIA'	,
            'WISCONSIN'	, 
            'WYOMING'	, 
            'GUAM'	, 
            'PUERTO RICO' ,	
            'VIRGIN ISLANDS'	],
  city_map : {
            'ALABAMA' : ['Birmingham','Montgomery','Mobile','Huntsville','Tuscaloosa'] ,
            'ALASKA' : ['Anchorage','Fairbanks','Juneau','Sitka','Ketchikan'] ,	
            'ARIZONA': ['Phoenix','Tucson','Mesa','Chandler','Glendale'] ,	
            'ARKANSAS': ['Little Rock','Fort Smith','Fayetteville','Springdale','Jonesboro'], 
            'CALIFORNIA': ['Los Angeles','San Diego','San Jose','San Francisco','Fresno','Sacramento' ] ,
            'COLORADO' : ['Denver','Colorado Springs','Aurora','Fort Collins','Lakewood'] , 
            'CONNECTICUT' : ['Bridgeport','New Haven','Stamford','Hartford','Waterbury'] ,	
            'DELAWARE' : ['Wilmington','Dover','Newark','Milford','Seaford'],
            'FLORIDA'	: ['Jacksonville','Miami','Tampa','St. Petersburg','Orlando','Tallahassee'], 
            'GEORGIA'	: ['Atlanta','Augusta','Columbus','Savannah','Athens'],
            'HAWAII' : ['Honolulu','Hilo','Kailua','Kapolei','Kaneohe'], 
            'IDAHO' : ['Boise','Nampa','Meridian','Idaho Falls','Pocatello'],	
            'ILLINOIS' : ['Chicago','Aurora','Rockford','Joliet','Naperville','Springfield' ], 	
            'INDIANA' : ['Indianapolis','Fort Wayne','Evansville','South Bend','Carmel'],	
            'IOWA' : ['Des Moines','Cedar Rapids','Davenport','Sioux City','Waterloo'],	
            'KANSAS' : ['Wichita','Overland Park','Kansas City','Topeka','Olathe'],	
            'KENTUCKY' : ['Louisville','Lexington','Bowling Green','Owensboro','Covington','Frankfort' ],	
            'LOUISIANA' : ['New Orleans','Baton Rouge','Shreveport','Lafayette','Lake Charles'],	
            'MAINE' : ['Portland','Lewiston','Bangor','South Portland','Auburn','	Augusta' ],	
            'MARYLAND' : ['Baltimore','Columbia','Germantown','Silver Spring','Waldorf','Annapolis' ],	
            'MASSACHUSETTS' : ['Boston','Worcester','Springfield','Lowell','Cambridge'],	
            'MICHIGAN' : ['Detroit','Grand Rapids','Warren','Sterling Heights','Ann Arbor','Lansing' ],
            'MINNESOTA'	: ['Minneapolis','Saint Paul','Rochester','Duluth','Bloomington'], 
            'MISSISSIPPI'	: ['Jackson','Gulfport','Hattiesburg','Southaven','Biloxi'], 
            'MISSOURI' : ['Kansas City','St Louis','Springfield','Independence','Columbia','Jefferson City'],	
            'MONTANA'	: ['Billings','Missoula','Great Falls','Bozeman','Butte','Helena'], 
            'NEBRASKA'	: ['Omaha','Lincoln','Bellevue','Grand Island','Kearney'], 
            'NEVADA'	: ['Las Vegas','Henderson','North Las Vegas','Reno','Sparks','Carson City'], 
            'NEW HAMPSHIRE'	: ['Manchester','Nashua	','Concord','Derry','Rochester'],
            'NEW JERSEY' : ['Newark','Jersey City','Paterson','Elizabeth','Edison','Trenton' ],	
            'NEW MEXICO' : ['Albuquerque','Las Cruces','Rio Rancho','Santa Fe','Roswell'],	
            'NEW YORK' : ['New York','Buffalo','Rochester','Yonkers','Syracuse','Albany' ],	
            'NORTH CAROLINA' : ['Charlotte','Raleigh','Greensboro','Durham','Winston-Salem'	],	
            'NORTH DAKOTA'	: ['Fargo','Bismarck','Grand Forks','Minot','West Fargo'], 
            'OHIO'	: ['Columbus','Cleveland','Cincinnati','Toledo','Akron'], 
            'OKLAHOMA' : ['Oklahoma','City','Tulsa','Norman','Broken Arrow','Lawton'],	
            'OREGON'	: ['Portland','Salem','Eugene','Gresham','Hillsboro'], 
            'PENNSYLVANIA' : ['Philadelphia','Pittsburgh','Allentown','Erie','Reading','Harrisburg'],	
            'RHODE ISLAND' : ['Providence','Warwick','Cranston','Pawtucket','East Providence'],	
            'SOUTH CAROLINA' : ['Columbia','Charleston','North Charleston','Mount Pleasant','Rock Hill'],	
            'SOUTH DAKOTA'	: ['Sioux Falls','Rapid City','Aberdeen','Brookings','Watertown','Pierre' ], 
            'TENNESSEE'	: ['Memphis','Nashville','Knoxville','Chattanooga','Clarksville'], 
            'TEXAS'	: ['Houston','San Antonio','Dallas','Austin','Fort Worth'],
            'UTAH'	: ['Salt Lake City','West Valley City','Provo','West Jordan','Orem'], 
            'VERMONT'	: ['Burlington','Essex','South Burlington','Colchester','Rutland','Montpelier' ], 
            'VIRGINIA'	: ['Virginia Beach','Norfolk','Chesapeake','Richmond','Newport News'], 
            'WASHINGTON'	: ['Seattle','Spokane','Tacoma','Vancouver','Bellevue','Olympia' ], 
            'WEST VIRGINIA'	: ['Charleston','Huntington','Parkersburg','Morgantown','Wheeling'],
            'WISCONSIN'	: ['Milwaukee','Madison','Green Bay','Kenosha','Racine'], 
            'WYOMING'	: ['Cheyenne','Casper','Laramie','Gillette','Rock Springs'], 
            'GUAM'	: ['Guam', 'Dededo', 'Yigo', 'Tamuning' , 'Mangilao' ], 
            'PUERTO RICO' : ['San Juan', 'Bayamón', 'Carolina', 'Ponce', 'Caguas', 'Guaynabo'],	
            'VIRGIN ISLANDS' : ['St Croix', 'Charlotte Amalie']
            }
};

});